### ISSUE TITLE
Track customer journeys throughout your SaaS

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/ksqldb-recipes#106]
**Describe the use case**

You have a SaaS company where your customers browse pages online - maybe you’re an online retailer in this case. You want to know what your customer's journey has been throughout the site so that you can do analytics or understand what exactly they did if they call in for support.  The ksqlDB output could be sent out to ElasticSearch.

This one seems pretty simple: make session windows per user and use a collect_list aggregator on all the pages they visited. Show some example queries accessing that page set.

**Provide the ksqlDB application**
Document the full set of ksqlDB statements that represent the use case.

N/A -- need to create ksqlDB code.  Key is tumbling windows with `COLLECT_LIST`

**Comment by rspurgeon** [comment]
@ybyzek two thoughts on this one:

- Minor obsevation, but just for clarity.  The title says "your SaaS", however, the description seems to describe a web retailer as opposed to what I traditionally think of software as a service.
- I'm trying to understand the meaningful difference between this recipe idea and the existing https://confluentinc.github.io/ksqldb-recipes/customer-360/clickstream/ which has user information, clicks, sessions, and other seemingly similar concepts.

Maybe this could be described slightly differently to capture the ksqlDB behaviors we want to highlight that are different than the existing clickstream recipe?

**Comment by ybyzek** [comment]
@rspurgeon 

> I'm trying to understand the meaningful difference between this recipe idea and the existing https://confluentinc.github.io/ksqldb-recipes/customer-360/clickstream/ which has user information, clicks, sessions, and other seemingly similar concepts.


I made the same comment in [the XLS](https://docs.google.com/spreadsheets/d/1NuSE66xfAvCGK162C6L2bx4dML-bokwFPShN5KmBfN4/edit?disco=AAAASB0GpMM) to which @MichaelDrogalis response was "Yeah that seems fine. Let's keep the framing on the idea of a customer journey and actually collect the page history with collect_list, but the bulk of that seems fine."  @MichaelDrogalis , please elaborate if you'd like, but my interpretation is that this new recipe should focus on a  new _use case_ of a customer journey of specific pages they visited (versus sessions, errors, etc as shown in clickstream) and should showcase the ksqlDB function [collect_list](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/aggregate-functions/#collect_list)
