### ISSUE TITLE
Predictive: Next Best Offer for Banking

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/ksqldb-recipes#110]
**Describe the use case**
Next best offer (also known as next best action) is a form of predictive analytics that helps marketers and their organizations better judge customer spending habits and guide marketing efforts toward connecting with customers to close a deal.

**Provide the ksqlDB application**

https://github.com/confluentinc/demo-scene/blob/master/industry-themes/next_best_offer_banking/ksql/next_best_offer.ksql

**Comment by sophiajiangg** [comment]
@ybyzek do we have any additional context for where and hw this use case was used to help build out the copy?

**Comment by ybyzek** [comment]
> @ybyzek do we have any additional context for where and hw this use case was used to help build out the copy?

@sophiajiangg the source is https://github.com/confluentinc/demo-scene/tree/master/industry-themes

> Building next best offer engines with session information (Banking or Insurance)
