### ISSUE TITLE
Update master branch to main

### ISSUE THREAD

**Issue by rspurgeon** [confluentinc/ksqldb-recipes#14]
`main` is the preferred nomenclature. Guidance from GitHub here: https://github.com/github/renaming

**Comment by rmoff** [comment]
+1. We can just do this, right @rspurgeon ? I think you have commit rights. Or tag who needs to action it.

**Comment by ybyzek** [comment]
+1.  There are 11 open PRs though, so I propose we do this when all PRs are merged?  (Just to avoid issues with name change with open PRs)

**Comment by ybyzek** [comment]
Done ✅

**Comment by rspurgeon** [comment]
Nice @ybyzek , thanks :-)
