### ISSUE TITLE
Resolve inconsistency between `VARCHAR` and `STRING`

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/ksqldb-recipes#146]
https://github.com/confluentinc/ksqldb-recipes/pull/131#discussion_r783591267

Looking for clarification on differentiation of `VARCHAR` vs `STRING` and when to use which.  I usually see `VARCHAR` in the context below, but `STRING` also works:

```
CREATE STREAM pages (
   page STRING, ....
```

We have recipes that reference both...

**Comment by mjsax** [comment]
ksqlDB uses `STRING` as synonym to `VARCHAR` -- so semantically there is no difference.

`VARCHAR` is the standard SQL type, even if it usually need a "max size" parameter that ksqlDB does not implement. -- `STRING` is no standard SQL type (seems to be syntactic sugar -- but sure why ksqlDB added it).

To avoid confusing users, it might be good to just pick either one and use it exclusively in all tutorials.

**Comment by ybyzek** [comment]
> To avoid confusing users, it might be good to just pick either one and use it exclusively in all tutorials.

@mjsax agree.  Which would be your recommendation, `VARCHAR` or `STRING`?

**Comment by mjsax** [comment]
I would go with `VARCHAR`.

**Comment by ybyzek** [comment]
Closing and moving to https://github.com/confluentinc/kafka-tutorials/issues/1044
