### ISSUE TITLE
All recipes: Replace `latest_by_offset` with `CREATE SOURCE TABLE`

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/ksqldb-recipes#158]
From @mjsax 

> Using latest_by_offset is outdated. We should use the new CREATE SOURCE TABLE instead.

See discussion in https://github.com/confluentinc/ksqldb-recipes/pull/144#discussion_r789872110

**Comment by mjsax** [comment]
Just to add more color: there are for sure cases when `latest_by_offset` might still make sense. We should decide on a case-by-case basis.

**Comment by ybyzek** [comment]
Note to self: this is how one recipe was updated to use `CREATE SOURCE TABLE`: https://github.com/confluentinc/ksqldb-recipes/commit/a051ebdc1785bf8344f30161b7d9bd6689b4a25a

**Comment by ybyzek** [comment]
Closing and moving to https://github.com/confluentinc/kafka-tutorials/issues/1041
