### ISSUE TITLE
Update all recipes to use `GRACE`

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/ksqldb-recipes#161]
https://www.confluent.io/blog/ksqldb-0-23-1-features-updates/#grace-period

> In ksqlDB 0.23, we added the ability to specify a GRACE PERIOD in the WITHIN clause for stream-stream joins. The GRACE PERIOD clause will become mandatory in a future release and is only optional for now to ensure backward compatibility. Thus, we highly encourage you to use the GRACE PERIOD clause right away.

Action: review all recipes and add `GRACE` where appropriate

**Comment by mjsax** [comment]
We plan to make `GRACE` also mandatory for windowed aggregations, so it's not just for stream-stream joins.

**Comment by ybyzek** [comment]
Closing and moving this issue to https://github.com/confluentinc/kafka-tutorials/issues/1040
