### ISSUE TITLE
Suggestions to improve internet-of-things activity recipe

### ISSUE THREAD

**Issue by mjsax** [confluentinc/ksqldb-recipes#85]
In https://confluentinc.github.io/ksqldb-recipes/anomaly-detection/internet-of-things/, why do we create `throughput_insufficient`? Seems less efficient (another broker roundtrip to write into a topic and read it back, and another persistent query) and "contradicts" our recommendation to write fewer (but more complex queries) if possible. The filter could just be part of the last join query.

**Comment by ybyzek** [comment]
@mjsax thanks for the suggestion, great idea.  PR available at https://github.com/confluentinc/ksqldb-recipes/pull/91
